# Generated by Django 4.2.16 on 2025-08-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('course', 'year', 'section', 'roll_number')},
        ),
    ]
