# Generated by Django 4.2.7 on 2025-08-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('login_verification', 'Login Verification'), ('registration', 'Registration Verification')], default='password_reset', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for OTP verification (optional)', max_length=15, null=True, unique=True),
        ),
    ]
