# Generated by Django 4.2.16 on 2025-08-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_add_integrity_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_room_time_slot',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_teacher_time_slot',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='unique_class_time_slot',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='valid_year_range',
        ),
        migrations.RemoveConstraint(
            model_name='timetableentry',
            name='valid_day_of_week',
        ),
    ]
